### ISSUE TITLE
Copy edit schema guide

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/citation-file-format#240]
This issue lists a number of things that should be taken care of when copy editing the schema guide before release:

- [x] Fix typos :roll_eyes: (in PR #277)
- [x] Optimize names  (✔️ Done for "transitive credit" in 95b61b008e3843480b9b29e6d36c999ecbae9737, Credit redirection left as heading)
E.g., for "transitive credit" (and perhaps "credit redirection"), also impacts https://github.com/citation-file-format/cffinit/issues/10
- [x] Fix #251 (in PR #273)
- [x] Mark `definitions.` keys as not to be used   (✔️: Definitions section intro contains hint now)
- [x] Unify wording: YAML uses "keys" and so are we (✔️ in PR #274)
- [x] Check if examples are in the right place
- [x] Use *Usage example**s*** if there is more than one? (✔️: Now only called *usage* and in a bullet)
- [x] Reformat key descriptions? (✔️: done as suggested in https://github.com/citation-file-format/citation-file-format/issues/240#issuecomment-886170125)
E.g., as `> ` quotes? See [below](#examplesection)
- [x] Check what parts in [the other edit of the schema guide](https://github.com/citation-file-format/citation-file-format/pull/220/files#diff-28af06810cb7c393bb9ba0787f608e4f97918cc6b304541ba867916f243b4a38) may be useful to have in the schema guide (e.g., the reference to the changelog?)
- [x] Add links, e.g., to YAML specs (Done for YAML specs, rest in #277)

**Note:** part of this work should probably be done in "pair copy editing" :hot_face: 

#### Example section <a href="#examplesection" id="examplesection">#</a>

This is an example section describing a key, I quite like the highlighting, it's similar to that suggested in #220.

Perhaps `required:`'s value should only be bold when it's `true`?

Note: no ***Usage example:*** heading, this is indicated by putting the examples in the quote as well.

---

### `cff-version`

- type: **string**
- required: **true**

> *The version of CFF used for providing the citation metadata.*
> ```yaml
> cff-version: "1.2.0"
> ```

**Comment by jspaaks** [comment]
FWIW both the emojis and the quoted descriptions are a little too much markup for my taste

**Comment by jspaaks** [comment]
For markup, what about this?

----

### `authors`

- **type**: array of [`definitions.person`](#definitionsperson) and/or [`definitions.entity`](#definitionsentity) objects.
- **required**: `true`
- **description**: The authors of a software or dataset.
- **usage**:<br><br>
    ```yaml
    authors:
      - given-names: Stephan
        family-names: Druskat
    ```
    ```yaml
    authors:
      - name: "The Research Software project"
    ```
    ```yaml
    authors:
      - given-names: Stephan
        family-names: Druskat
      - name: "The Research Software project"
    ```

**Comment by sdruskat** [comment]
I like it, let's do it like this!

**Comment by sdruskat** [comment]
All done :)
